### ISSUE TITLE
Memory leak when trying to enroll finger

### ISSUE THREAD

**Issue by AbhishekGahlot** [luksan/pyfprint#4]
Here is the code and output
import pyfprint
x = pyfprint.discover_devices()[0]
y=x.enroll_finger()

Output: swig/python detected a memory leak of type 'struct fp_print_data *', no destructor found.

**Comment by fiatjaf** [comment]
I got this a lot. This library is great, but it has these problems and is abandoned. The solution is to use the C library directly.
